name: AurexCountdown
version: 1.1.0
main: com.example.demo.AurexCountdown
api-version: '1.21'
description: A simple countdown plugin for players.
commands:
  countdown:
    description: Player countdown commands.
    aliases: [aurexcd]
  countdownadmin:
    description: Admin countdown commands.
    aliases: [aurexcdadmin]
permissions:
  countdown.start:
    description: Allows a player to start a countdown.
    default: true
  countdown.pause:
    description: Allows a player to pause their countdown.
    default: true
  countdown.resume:
    description: Allows a player to resume their countdown.
    default: true
  countdown.reset:
    description: Allows a player to reset their countdown.
    default: true
  countdown.cancel:
    description: Allows a player to cancel their countdown.
    default: true
  countdown.add:
    description: Allows a player to add time to their countdown.
    default: true
  countdown.remove:
    description: Allows a player to remove time from their countdown.
    default: true
  countdown.reload:
    description: Allows a player to reload the config.
    default: op
  countdown.admin:
    description: Allows an admin to control other players' countdowns.
    default: op
